title: My Awesome Home
views:
    # View tab title.
  - title: Example
    panel: true
    # Makes the first card fill the view
    cards:
        # The markdown card will render markdown text.
      - type: markdown
        title: Lovelace
        content: >
          Welcome to your **Lovelace UI**.

  - type: entities
    title: Entities card sample
    show_header_toggle: true
    entities:
      - light.fibarodimmersov

